# typed: false
# frozen_string_literal: true

# This file was generated by Homebrew. DO NOT EDIT.
# If you have any suggestions, please open an issue at:
# https://github.com/Homebrew/homebrew-core/issues

class Prefix < Formula
  desc "Automatically organizes files from a dump directory based on filename patterns"
  homepage "https://github.com/shubhdevelop/prefix"
  # TODO: Replace v1.0.0 with the actual version tag
  url "https://github.com/shubhdevelop/prefix/archive/refs/tags/v1.0.0.tar.gz"
  # TODO: Replace with actual SHA256 checksum from the release
  sha256 "YOUR_SHA256_CHECKSUM_HERE"
  license "MIT"
  head "https://github.com/shubhdevelop/prefix.git", branch: "main"

  depends_on "go" => :build

  def install
    # Build the binary
    system "go", "build", "-trimpath", "-ldflags=-s -w", "-o", bin/"prefix", "."
    
    # Install example config file
    # Users can copy this to ~/.prefix.yaml and customize it
    pkgshare.install "config.example.yaml"
    
    # Install service management script
    bin.install "prefix-service.sh" => "prefix-service"
  end

  test do
    # Test that the binary exists and runs
    assert_match "File organizer starting", shell_output("#{bin}/prefix 2>&1", 1)
  end

  def caveats
    <<~EOS
      To get started:
      1. Copy the example config: cp #{pkgshare}/config.example.yaml ~/.prefix.yaml
      2. Edit ~/.prefix.yaml with your dump directory and destinations
      3. Run manually: prefix
      
      To run as a background service (starts on boot):
      1. Install the LaunchAgent: prefix-service install
      2. Check status: prefix-service status
      3. View logs: prefix-service logs
      
      Service management commands:
      - prefix-service start    # Start the service
      - prefix-service stop     # Stop the service
      - prefix-service restart  # Restart the service
      - prefix-service uninstall # Remove the service
    EOS
  end
end
